### ISSUE TITLE
WeatherTodo with Fabric doesn't work with fuse preview

### ISSUE THREAD

**Issue by COCPORN** [Duckers/WeatherTodo#12]
Click on a todo in the list, and it will fail with:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Uno.UX.PropertyObject.EmulatePropertyChanged(PropertyObject obj, Selector sel, IPropertyListener origin) in C:\Users\larsd\AppData\Local\Fusetools\Packages\UnoCore\0.47.10\source\uno\ux\$.uno:line 363
   at Outracks.Simulator.Runtime.UxProperty`1.Set(PropertyObject obj, T value, IPropertyListener origin) in C:\Users\larsd\Projects\Fuse\WeatherTodo\build\Local\Preview\preamble\$.uno:line 62
   at Uno.UX.Property`1.SetAsObject(PropertyObject obj, Object value, IPropertyListener origin) in C:\Users\larsd\AppData\Local\Fusetools\Packages\UnoCore\0.47.10\source\uno\ux\$.uno:line 305
   at Fuse.Reactive.Property.Subscription.SetExclusive(Object value) in C:\Users\larsd\AppData\Local\Fusetools\Packages\Fuse.Reactive.Expressions\0.47.1\$.uno:line 668
   at Fuse.Reactive.ExpressionBinding.WriteBack(Object value) in C:\Users\larsd\AppData\Local\Fusetools\Packages\Fuse.Reactive.Bindings\0.47.1\$.uno:line 814
   at Fuse.Reactive.DataBinding.Uno.UX.IPropertyListener.OnPropertyChanged(PropertyObject obj, Selector prop) in C:\Users\larsd\AppData\Local\Fusetools\Packages\Fuse.Reactive.Bindings\0.47.1\$.uno:line 297
   at Uno.UX.PropertyObject.OnPropertyChanged(Selector property, IPropertyListener origin) in C:\Users\larsd\AppData\Local\Fusetools\Packages\UnoCore\0.47.10\source\uno\ux\$.uno:line 351
   at Uno.UX.PropertyObject.OnPropertyChanged(Selector property) in C:\Users\larsd\AppData\Local\Fusetools\Packages\UnoCore\0.47.10\source\uno\ux\$.uno:line 358
   at Fuse.Selection.Selection.OnSelectionChanged(How how) in C:\Users\larsd\AppData\Local\Fusetools\Packages\Fuse.Selection\0.47.1\$.uno:line 767
   at Fuse.Selection.Selection.Remove(String value) in C:\Users\larsd\AppData\Local\Fusetools\Packages\Fuse.Selection\0.47.1\$.uno:line 720
   at Fuse.Selection.Selection.SetValue(String value, IPropertyListener origin) in C:\Users\larsd\AppData\Local\Fusetools\Packages\Fuse.Selection\0.47.1\$.uno:line 702
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Outracks.Simulator.Runtime.TryInvokeExtension.Try(Func`1 func)
   at Outracks.Simulator.Runtime.TryInvokeExtension.TryInvoke(MethodInfo mi, Object obj, Object[] value)
   at Outracks.Simulator.Runtime.CompiledTypeReflection.CallDynamic(Object obj, TypeMemberName methodName, Object[] arguments)
   at Outracks.Fuse.Preview.RuntimeObjectPoker.<HookUpReflectionInterface>b__e(Object a, String b, Object[] c)
   at Outracks.Simulator.Reflection.DelegateReflection.Outracks.Simulator.Runtime.IReflection.CallDynamic(Object instance, TypeMemberName methodName, Object[] arguments) in C:\Users\larsd\AppData\Local\Fusetools\Fuse\App\app-0.36.0.11631\Packages\Outracks.Simulator.Reflection.Uno\0.0.0\$.uno:line 86
   at Outracks.Simulator.Runtime.ScopeClosure.Evaluate(CallDynamicMethod m) in C:\Users\larsd\AppData\Local\Fusetools\Fuse\App\app-0.36.0.11631\Packages\Outracks.Simulator.Client.Uno\0.1.0\runtime\$.uno:line 173
   at Outracks.Simulator.Bytecode.Expression.Match[T](Func`2 a1, Func`2 a2, Func`2 a3, Func`2 a4, Func`2 a5, Func`2 a6, Func`2 a7, Func`2 a8, Func`2 a9, Func`2 a10, Func`2 a11, Func`2 a12, Func`2 a13, Func`2 a15, Func`2 a16) in C:\Users\larsd\AppData\Local\Fusetools\Fuse\App\app-0.36.0.11631\Packages\Outracks.Simulator.Protocol.Uno\0.0.0\bytecode\$.uno:line 119
   at Outracks.Simulator.Runtime.ScopeClosure.Evaluate(Expression expression) in C:\Users\larsd\AppData\Local\Fusetools\Fuse\App\app-0.36.0.11631\Packages\Outracks.Simulator.Client.Uno\0.1.0\runtime\$.uno:line 131
   at Outracks.Simulator.Runtime.ScopeClosure.Execute(IEnumerable`1 statements) in C:\Users\larsd\AppData\Local\Fusetools\Fuse\App\app-0.36.0.11631\Packages\Outracks.Simulator.Client.Uno\0.1.0\runtime\$.uno:line 117
   at Outracks.Simulator.Runtime.ScopeClosure.Execute(Lambda lambda, Object[] arguments) in C:\Users\larsd\AppData\Local\Fusetools\Fuse\App\app-0.36.0.11631\Packages\Outracks.Simulator.Client.Uno\0.1.0\runtime\$.uno:line 107
   at Outracks.Simulator.Runtime.LambdaClosure.Func(Object a1, Object a2, Object a3) in C:\Users\larsd\AppData\Local\Fusetools\Fuse\App\app-0.36.0.11631\Packages\Outracks.Simulator.Client.Uno\0.1.0\runtime\$.uno:line 492
   at Outracks.Simulator.Runtime.LambdaClosure.Action(Object a1, Object a2, Object a3) in C:\Users\larsd\AppData\Local\Fusetools\Fuse\App\app-0.36.0.11631\Packages\Outracks.Simulator.Client.Uno\0.1.0\runtime\$.uno:line 407
   at Outracks.Simulator.Runtime.UxProperty`1.Set(PropertyObject obj, T value, IPropertyListener origin) in C:\Users\larsd\Projects\Fuse\WeatherTodo\build\Local\Preview\preamble\$.uno:line 61
   at Uno.UX.Property`1.SetAsObject(PropertyObject obj, Object value, IPropertyListener origin) in C:\Users\larsd\AppData\Local\Fusetools\Packages\UnoCore\0.47.10\source\uno\ux\$.uno:line 305
   at Uno.UX.Property.SetAsObject(Object value, IPropertyListener origin) in C:\Users\larsd\AppData\Local\Fusetools\Packages\UnoCore\0.47.10\source\uno\ux\$.uno:line 283
   at Fuse.Reactive.DataBinding.SetTarget(Object value) in C:\Users\larsd\AppData\Local\Fusetools\Packages\Fuse.Reactive.Bindings\0.47.1\$.uno:line 274
   at Fuse.Reactive.DataBinding.TryPushAsValue(Object newValue) in C:\Users\larsd\AppData\Local\Fusetools\Packages\Fuse.Reactive.Bindings\0.47.1\$.uno:line 350
   at Fuse.Reactive.DataBinding.PushValue(Object newValue) in C:\Users\larsd\AppData\Local\Fusetools\Packages\Fuse.Reactive.Bindings\0.47.1\$.uno:line 340
   at Fuse.Reactive.DataBinding.NewValue(Object value) in C:\Users\larsd\AppData\Local\Fusetools\Packages\Fuse.Reactive.Bindings\0.47.1\$.uno:line 318
   at Fuse.Reactive.ExpressionBinding.Fuse.Reactive.IListener.OnNewData(IExpression source, Object obj) in C:\Users\larsd\AppData\Local\Fusetools\Packages\Fuse.Reactive.Bindings\0.47.1\$.uno:line 841
   at Fuse.Reactive.Property.Subscription.PushValue() in C:\Users\larsd\AppData\Local\Fusetools\Packages\Fuse.Reactive.Expressions\0.47.1\$.uno:line 686
   at Fuse.Reactive.Property.Subscription.Uno.UX.IPropertyListener.OnPropertyChanged(PropertyObject obj, Selector prop) in C:\Users\larsd\AppData\Local\Fusetools\Packages\Fuse.Reactive.Expressions\0.47.1\$.uno:line 681
   at Uno.UX.PropertyObject.OnPropertyChanged(Selector property, IPropertyListener origin) in C:\Users\larsd\AppData\Local\Fusetools\Packages\UnoCore\0.47.10\source\uno\ux\$.uno:line 351
   at Uno.UX.PropertyObject.EmulatePropertyChanged(PropertyObject obj, Selector sel, IPropertyListener origin) in C:\Users\larsd\AppData\Local\Fusetools\Packages\UnoCore\0.47.10\source\uno\ux\$.uno:line 363
   at Outracks.Simulator.Runtime.UxProperty`1.Set(PropertyObject obj, T value, IPropertyListener origin) in C:\Users\larsd\Projects\Fuse\WeatherTodo\build\Local\Preview\preamble\$.uno:line 62
   at Uno.UX.Property`1.SetAsObject(PropertyObject obj, Object value, IPropertyListener origin) in C:\Users\larsd\AppData\Local\Fusetools\Packages\UnoCore\0.47.10\source\uno\ux\$.uno:line 305
   at Uno.UX.Property.SetAsObject(Object value, IPropertyListener origin) in C:\Users\larsd\AppData\Local\Fusetools\Packages\UnoCore\0.47.10\source\uno\ux\$.uno:line 283
   at Fuse.Reactive.DataBinding.SetTarget(Object value) in C:\Users\larsd\AppData\Local\Fusetools\Packages\Fuse.Reactive.Bindings\0.47.1\$.uno:line 274
   at Fuse.Reactive.DataBinding.TryPushAsValue(Object newValue) in C:\Users\larsd\AppData\Local\Fusetools\Packages\Fuse.Reactive.Bindings\0.47.1\$.uno:line 350
   at Fuse.Reactive.DataBinding.PushValue(Object newValue) in C:\Users\larsd\AppData\Local\Fusetools\Packages\Fuse.Reactive.Bindings\0.47.1\$.uno:line 340
   at Fuse.Reactive.DataBinding.Fuse.Reactive.IObserver.OnSet(Object newValue) in C:\Users\larsd\AppData\Local\Fusetools\Packages\Fuse.Reactive.Bindings\0.47.1\$.uno:line 188
   at Fuse.Reactive.Observable.Set.OnPerform(IList`1 sub) in C:\Users\larsd\AppData\Local\Fusetools\Packages\Fuse.Reactive.JavaScript\0.47.1\$.uno:line 849
   at Fuse.Reactive.Observable.Operation.Perform() in C:\Users\larsd\AppData\Local\Fusetools\Packages\Fuse.Reactive.JavaScript\0.47.1\$.uno:line 800
   at Fuse.Reactive.ThreadWorker.ProcessUIMessages() in C:\Users\larsd\AppData\Local\Fusetools\Packages\Fuse.Reactive.JavaScript\0.47.1\$.uno:line 1355
   at Fuse.UpdateListener.Invoke() in C:\Users\larsd\AppData\Local\Fusetools\Packages\Fuse.Common\0.47.1\$.uno:line 3004
   at Fuse.UpdateManager.ProcessListeners(Stage stage, List`1& _exceptions) in C:\Users\larsd\AppData\Local\Fusetools\Packages\Fuse.Common\0.47.1\$.uno:line 3311
```

**Comment by COCPORN** [comment]
This works in the latest preview of 0.36.
